make
echo dfljglsdfjgsdfghsdfgsdfgsdfugsudhlfugsdfuhgsdfuglhsergsdfugldfljglsdfjgsdfghsdfgsdfgsdfugsudhlfugsdfuhgsdfuglhsergsdfugldfljglsdfjgsdfghsdfgsdfgsdfugsudhlfugsdfuhgsdfuglhsergsdfugldfljglsdfjgsdfghsdfgsdfgsdfugsudhlfugsdfuhgsdfuglhsergsdfugldfljglsdfjgsdfghsdfgsdfgsdfugsudhlfugsdfuhgsdfuglhsergsdfugldfljglsdfjgsdfghsdfgsdfgsdfugsudhlfugsdfuhgsdfuglhsergsdfugldfljglsdfjgsdfghsdfgsdfgsdfugsudhlfugsdfuhgsdfuglhsergsdfugldfljglsdfjgsdfghsdfgsdfgsdfugsudhlfugsdfuhgsdfuglhsergsdfugldfljglsdfjgsdfghsdfgsdfgsdfugsudhlfugsdfuhgsdfuglhsergsdfugldfljglsdfjgsdfghsdfgsdfgsdfugsudhlfugsdfuhgsdfuglhsergsdfugldfljglsdfjgsdfghsdfgsdfgsdfugsudhlfugsdfuhgsdfuglhsergsdfugl>1
./xor -c "cat 1" -g "./gen -g key" > 2
./xor -c "cat 2" -g "./gen -f key" > 3

